let data = [
  {
    id: 1,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 4,
    price: 111,
  },
  {
    id: 2,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 5,
    price: 58,
  },
  {
    id: 3,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 3,
    price: 79,
  },
  {
    id: 4,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 4,
    price: 185,
  },
  {
    id: 5,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 5,
    price: 350,
  },
  {
    id: 6,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 4,
    price: 325,
  },
  {
    id: 7,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 3,
    price: 100,
  },
  {
    id: 8,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 4,
    price: 88,
  },
  {
    id: 9,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 5,
    price: 123,
  },
  {
    id: 10,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 5,
    price: 225,
  },
];
export default data;
