let data = [
  {
    id: 1,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description:
      "This impressive home is a perfect place for a weekend getaway! Take in the scenery by hiking one of the many nearby trails, if you like.",
    rating: 0,
    price: 111,
    location: "Stowe, VT",
  },
  {
    id: 2,
    title: "Picturesque Location!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Xt8wOi_eB1KqPgHPZuYUAAHaE0%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 0,
    price: 408,
    location: "Stowe, VT",
  },
  {
    id: 3,
    title: "Picturesque Location!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.Vanisk-SOekVvjbIcxD1XAHaE2%26pid%3DApi&f=1",
    description: "A cozy apartment for a warm winter stay!",
    rating: 0,
    price: 79,
    location: "Stowe, VT",
  },
  {
    id: 4,
    title: "Picturesque Location!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.Xt8wOi_eB1KqPgHPZuYUAAHaE0%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 0,
    price: 185,
    location: "Stowe, VT",
  },
  {
    id: 5,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy apartment for a warm winter stay!",
    rating: 0,
    price: 350,
    location: "Fall River, MA",
  },
  {
    id: 6,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.2Un-nkS4FVE7CDACGY1-rgHaEc%26pid%3DApi&f=1",
    description: "A cozy house for a warm winter stay!",
    rating: 0,
    price: 225,
    location: "Fall River, MA",
  },
  {
    id: 7,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse2.mm.bing.net%2Fth%3Fid%3DOIP.2Un-nkS4FVE7CDACGY1-rgHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 0,
    price: 350,
    location: "Manchester-by-the-Sea, MA",
  },
  {
    id: 8,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.mm.bing.net%2Fth%3Fid%3DOIP.sMDxmZzr97vLn3rFMBbEigHaE8%26pid%3DApi&f=1",
    description: "A cozy apartment for a warm winter stay!",
    rating: 0,
    price: 88,
    location: "Manchester-by-the-Sea, MA",
  },
  {
    id: 9,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse1.mm.bing.net%2Fth%3Fid%3DOIP.ZXOHGFvyd2szOaMh2PNXpwHaE8%26pid%3DApi&f=1",
    description: "A cozy house for a warm winter stay!",
    rating: 0,
    price: 123,
    location: "Burlington, VT",
  },
  {
    id: 10,
    title: "A Hygge Home!",
    img: "https://external-content.duckduckgo.com/iu/?u=https%3A%2F%2Ftse3.explicit.bing.net%2Fth%3Fid%3DOIP.YpKaoxx2Dd2K1zmHS_l7XQHaEc%26pid%3DApi&f=1",
    description: "A cozy cabin for a warm winter stay!",
    rating: 0,
    price: 225,
    location: "Burlington, VT",
  },
];
export default data;
